inherit_from: .rubocop_todo.yml

# .rubocop.yml
plugins:
  - rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
  - "db/schema.rb"
  - "Gemfile"
  - "lib/tasks/*.rake"
  - "bin/*"
  - "config/puma.rb"
  - "config/spring.rb"
  - "config/environments/development.rb"
  - "config/environments/production.rb"
  - "spec/spec_helper.rb"

Layout/LineLength:
  Max: 150

Layout/IndentationWidth:
  Width: 2 

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case #default
  AllowedPatterns:
    - '.*_oauth2'  # allow method names ending with _oauth2 as it MUST be named this way

Naming/ClassAndModuleCamelCase:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/For:
    EnforcedStyle: each
Style/IfUnlessModifier:
  Enabled: true
Style/NegatedIf:
  Enabled: true # use `unless` instead of `!if`
Style/UnlessElse:
  Enabled: true # disallow unless with else
Style/WhileUntilModifier:
  Enabled: true

Naming/PredicatePrefix:
  Enabled: true
  NamePrefix:
    - is_
    - does_
    - can_
  ForbiddenPrefixes:
    - is_
    - does_
    - can_

Naming/ConstantName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
  AllowedPatterns:
    - '.*_oauth2'  # allow google_oauth2

# Ruby's default files don't define classes the way rubocop likes so we do away with it
Naming/FileName:
  Enabled: false


Rails/PluralizationGrammar:
  Enabled: true # enforce plural table names

Rails/HasAndBelongsToMany:
  Enabled: true # ensure HABTM join table names follow convention

Rails/InverseOf:
  Enabled: true

Rails/SaveBang:
  Enabled: true # enforce save! instead of save for reliability

Rails/SkipsModelValidations:
  Enabled: true # avoid update_all, decrement, etc.

Rails/TimeZone:
  Enabled: true # enforce Time.zone.now instead of Time.now

Style/DefWithParentheses:
  Enabled: true # enforce def with parentheses when args are present

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/IdenticalConditionalBranches:
  Enabled: true # helps with DRY

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true


# Exclusions

# Autogenerated from Rolify
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

# These are generated files from Ruby gems and are not going to be linted for now
# seeds.rb has some long comments
Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'db/seeds.rb'